server {
    listen 80;

    # Sirve tu perfil estático: index.html, libro-de-visitas.js, etc.
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Reverse proxy: todo lo que llegue a /api/ se reenvía al servicio "api"
    # de Compose (se alcanza por su NOMBRE, no por IP, gracias a la red interna).
    location /api/ {
        proxy_pass http://api:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
